services:
  api:
    build: ./backend
    container_name: yt_tldr_api
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    networks:
      - proxy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: yt_tldr_frontend
    depends_on:
      - api
    networks:
      - proxy

networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
